### ISSUE TITLE
The names of "graphic/spritetypes.h" and "graphic/spritetypes.cc" do not make sense.

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/ugdk#29]
All they have is the function action::LoadSpriteAnimationTableFromFile().

**Comment by henriquegemignani** [comment]
The types that would be defined there are defined in <ugdk/graphic.h> since they're simple typedefs. This header then includes the necessary headers to use these types.

The filename could be improved. Suggestions?

**Comment by Kazuo256** [comment]
Where are the types defined?

If the only thing in these files is going to be that function, then I suggest naming them simply "loadspriteanimationtable.h" and "loadspriteanimationtable.cc".

**Comment by henriquegemignani** [comment]
The types would be defined on that file, but they're "forward declared" in
graphics.h. Since they're just typedefs, the only thing left for the header
to do, is include the headers that defines the types used in the typedefs.
And this is actually the main use of the file.

## 

Henrique Gemignani Passos Lima
http://uspgamedev.org/

2014-10-26 15:21 GMT-02:00 Wilson Kazuo Mizutani notifications@github.com:

**Comment by Kazuo256** [comment]
Then I suppose it is the function LoadSpriteAnimationTableFromFile() that is in the wrong place.
